### ISSUE TITLE
Move format to extra yaml prop to allow for file extension customization

### ISSUE THREAD

**Issue by iDVB** [sbstjn/serverless-stack-output#10]
It would be helpful if this plugin allowed for...
```yaml
custom:
  output:
    format: toml # toml, yaml, yml, and json format is available
    file: .build/.env
```
This way you can name the file anything you want.

Helps with trying to standardize with other plugins like this... 
https://github.com/mrsteele/dotenv-webpack

For the moment, I'm simply relying on the above plugin's ability to look for a different name other than `.env`.
