### ISSUE TITLE
Plugin executes out of order relative to other serverless plugins

### ISSUE THREAD

**Issue by jhslinkman** [sbstjn/serverless-stack-output#18]
Consider a serverless.yml

```
...
plugins:
    - serverless-stack-ouput
    - other-plugin

custom:
  output:
    file: stack-output.yml
...
```

where `other-plugin` processes `stack-output.yml` output by this file. As it's currently implemented, other-plugin will being processing before `serverless-stack-output` finished. The offending line is in the [StackOutputPlugin#process](https://github.com/sbstjn/serverless-stack-output/blob/master/src/plugin.ts#L140) method. If that method is changed to return a promise, everything works as expected.
