### ISSUE TITLE
Fails silently if given directory path doesn't exist

### ISSUE THREAD

**Issue by kasandravtv** [sbstjn/serverless-stack-output#32]
When using a serverless.yml like:
```yaml

plugins:
  - serverless-stack-output

custom:
  output:
    file: .serverless-outputs/stackOutput.json
```
Then if the given directory `.serverless-outputs` does not exists, it fails silently. I would expect any given folder that doesn't exist to be created, so we don't need to have a .gitkeep file in our repo.
